export const SignInSignUpAction = {
  REDUX: "REDUX",
  SIGNUP: "SIGNUP",
  FETCH_API_LOGIN: "FETCH_API_LOGIN",
  LOGOUT: "LOGOUT",
  DATA_ALL: "DATA_ALL",
  SEARCH: "SEARCH",
  SUGGEST: "SUGGEST",
  SET_ADMIN: "SET_ADMIN",
  SET_DATA_NEW_USER_NAME: "SET_DATA_NEW_USER_NAME",
  SET_DATA_NEW_USER_EMAIL: "SET_DATA_NEW_USER_EMAIL",
  SET_DATA_NEW_USER_PASSWORD: "SET_DATA_NEW_USER_PASSWORD",
  SET_DATA_NEW_USER_AGE: "SET_DATA_NEW_USER_AGE",

  //set data create
  SET_DATA_CREATE_USER:"SET_DATA_CREATE_USER",
  VALID_USER_NAME:"VALID_USER_NAME",
  VALID_USER_EMAIL:"VALID_USER_EMAIL",
  VALIDATE_FORM:"VALIDATE_FORM",
};
